# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.config_project = QtWidgets.QWidget()
        self.config_project.setObjectName("config_project")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config_project)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.app4 = QtWidgets.QLineEdit(self.config_project)
        self.app4.setObjectName("app4")
        self.gridLayout_2.addWidget(self.app4, 4, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.config_project)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.config_project)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.app1 = QtWidgets.QLineEdit(self.config_project)
        self.app1.setObjectName("app1")
        self.gridLayout_2.addWidget(self.app1, 4, 1, 1, 1)
        self.nameProject = QtWidgets.QLineEdit(self.config_project)
        self.nameProject.setObjectName("nameProject")
        self.gridLayout_2.addWidget(self.nameProject, 0, 1, 1, 4)
        self.specBid = QtWidgets.QLineEdit(self.config_project)
        self.specBid.setObjectName("specBid")
        self.gridLayout_2.addWidget(self.specBid, 2, 1, 1, 4)
        self.app2 = QtWidgets.QLineEdit(self.config_project)
        self.app2.setObjectName("app2")
        self.gridLayout_2.addWidget(self.app2, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.config_project)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.config_project)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.ipAddress1 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress1.setObjectName("ipAddress1")
        self.gridLayout_2.addWidget(self.ipAddress1, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.config_project)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.config_project)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.app3 = QtWidgets.QLineEdit(self.config_project)
        self.app3.setObjectName("app3")
        self.gridLayout_2.addWidget(self.app3, 4, 3, 1, 1)
        self.timeIn = QtWidgets.QTimeEdit(self.config_project)
        self.timeIn.setObjectName("timeIn")
        self.gridLayout_2.addWidget(self.timeIn, 3, 1, 1, 1)
        self.ipAddress2 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress2.setObjectName("ipAddress2")
        self.gridLayout_2.addWidget(self.ipAddress2, 5, 2, 1, 1)
        self.timeOut = QtWidgets.QTimeEdit(self.config_project)
        self.timeOut.setObjectName("timeOut")
        self.gridLayout_2.addWidget(self.timeOut, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.config_project)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.ipAddress4 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress4.setObjectName("ipAddress4")
        self.gridLayout_2.addWidget(self.ipAddress4, 5, 4, 1, 1)
        self.dateIn = QtWidgets.QDateEdit(self.config_project)
        self.dateIn.setObjectName("dateIn")
        self.gridLayout_2.addWidget(self.dateIn, 3, 3, 1, 2)
        self.numBid = QtWidgets.QLineEdit(self.config_project)
        self.numBid.setObjectName("numBid")
        self.gridLayout_2.addWidget(self.numBid, 1, 1, 1, 1)
        self.numberRev = QtWidgets.QLineEdit(self.config_project)
        self.numberRev.setObjectName("numberRev")
        self.gridLayout_2.addWidget(self.numberRev, 1, 3, 1, 1)
        self.cache = QtWidgets.QCheckBox(self.config_project)
        self.cache.setObjectName("cache")
        self.gridLayout_2.addWidget(self.cache, 1, 4, 1, 1)
        self.ipAddress3 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress3.setObjectName("ipAddress3")
        self.gridLayout_2.addWidget(self.ipAddress3, 5, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.config_project)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 6, 0, 1, 5)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.config_project, "")
        self.people = QtWidgets.QWidget()
        self.people.setObjectName("people")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.people)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.people, "")
        self.stage_4 = QtWidgets.QWidget()
        self.stage_4.setObjectName("stage_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.stage_4)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.title = QtWidgets.QTextEdit(self.stage_4)
        self.title.setObjectName("title")
        self.gridLayout_8.addWidget(self.title, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.stage_4)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.target = QtWidgets.QTextEdit(self.stage_4)
        self.target.setObjectName("target")
        self.gridLayout_8.addWidget(self.target, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.stage_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.stage_4, "")
        self.stage_1 = QtWidgets.QWidget()
        self.stage_1.setObjectName("stage_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.stage_1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stage_1_text = QtWidgets.QTextEdit(self.stage_1)
        self.stage_1_text.setObjectName("stage_1_text")
        self.gridLayout_4.addWidget(self.stage_1_text, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.stage_1, "")
        self.stage_2 = QtWidgets.QWidget()
        self.stage_2.setObjectName("stage_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.stage_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stage_2_text = QtWidgets.QTextEdit(self.stage_2)
        self.stage_2_text.setObjectName("stage_2_text")
        self.gridLayout_6.addWidget(self.stage_2_text, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.stage_2, "")
        self.stage_3 = QtWidgets.QWidget()
        self.stage_3.setObjectName("stage_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.stage_3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stage_3_text = QtWidgets.QTextEdit(self.stage_3)
        self.stage_3_text.setObjectName("stage_3_text")
        self.gridLayout_7.addWidget(self.stage_3_text, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.stage_3, "")
        self.configure = QtWidgets.QWidget()
        self.configure.setObjectName("configure")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.configure)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_13.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.configure, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор"))
        self.label_7.setText(_translate("MainWindow", "Экземляры"))
        self.label_3.setText(_translate("MainWindow", "Название проекта"))
        self.label_9.setText(_translate("MainWindow", "Номер ревизии"))
        self.label_4.setText(_translate("MainWindow", "Номер заявки"))
        self.label_5.setText(_translate("MainWindow", "Время публикации"))
        self.label_6.setText(_translate("MainWindow", "Описание заявки"))
        self.label_8.setText(_translate("MainWindow", "IP адрес"))
        self.cache.setText(_translate("MainWindow", "Сброс кеша"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_project), _translate("MainWindow", "Значения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.people), _translate("MainWindow", "Команда публикации"))
        self.label.setText(_translate("MainWindow", "Колонтитул"))
        self.label_2.setText(_translate("MainWindow", "Цель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stage_4), _translate("MainWindow", "Цель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stage_1), _translate("MainWindow", "Этап 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stage_2), _translate("MainWindow", "Этап 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stage_3), _translate("MainWindow", "Этап 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configure), _translate("MainWindow", "Настройки"))

