# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.config_project = QtWidgets.QWidget()
        self.config_project.setObjectName("config_project")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config_project)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.numBid = QtWidgets.QLineEdit(self.config_project)
        self.numBid.setObjectName("numBid")
        self.gridLayout_2.addWidget(self.numBid, 1, 1, 1, 1)
        self.app4 = QtWidgets.QLineEdit(self.config_project)
        self.app4.setObjectName("app4")
        self.gridLayout_2.addWidget(self.app4, 4, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.config_project)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.config_project)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.config_project)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.ipAddress3 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress3.setObjectName("ipAddress3")
        self.gridLayout_2.addWidget(self.ipAddress3, 5, 3, 1, 1)
        self.app3 = QtWidgets.QLineEdit(self.config_project)
        self.app3.setObjectName("app3")
        self.gridLayout_2.addWidget(self.app3, 4, 3, 1, 1)
        self.ipAddress1 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress1.setObjectName("ipAddress1")
        self.gridLayout_2.addWidget(self.ipAddress1, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.config_project)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.portApp = QtWidgets.QLineEdit(self.config_project)
        self.portApp.setObjectName("portApp")
        self.gridLayout_2.addWidget(self.portApp, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.config_project)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.config_project)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.timeIn = QtWidgets.QTimeEdit(self.config_project)
        self.timeIn.setObjectName("timeIn")
        self.gridLayout_2.addWidget(self.timeIn, 3, 1, 1, 1)
        self.svn = QtWidgets.QLineEdit(self.config_project)
        self.svn.setObjectName("svn")
        self.gridLayout_2.addWidget(self.svn, 6, 3, 1, 2)
        self.cache = QtWidgets.QCheckBox(self.config_project)
        self.cache.setEnabled(True)
        self.cache.setAcceptDrops(False)
        self.cache.setChecked(False)
        self.cache.setObjectName("cache")
        self.gridLayout_2.addWidget(self.cache, 1, 4, 1, 1)
        self.timeOut = QtWidgets.QTimeEdit(self.config_project)
        self.timeOut.setObjectName("timeOut")
        self.gridLayout_2.addWidget(self.timeOut, 3, 2, 1, 1)
        self.numberRev = QtWidgets.QLineEdit(self.config_project)
        self.numberRev.setObjectName("numberRev")
        self.gridLayout_2.addWidget(self.numberRev, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.config_project)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.app2 = QtWidgets.QLineEdit(self.config_project)
        self.app2.setObjectName("app2")
        self.gridLayout_2.addWidget(self.app2, 4, 2, 1, 1)
        self.nameProject = QtWidgets.QLineEdit(self.config_project)
        self.nameProject.setObjectName("nameProject")
        self.gridLayout_2.addWidget(self.nameProject, 0, 1, 1, 4)
        self.ipAddress2 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress2.setObjectName("ipAddress2")
        self.gridLayout_2.addWidget(self.ipAddress2, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.config_project)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.config_project)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 8, 0, 1, 5)
        self.ipAddress4 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress4.setObjectName("ipAddress4")
        self.gridLayout_2.addWidget(self.ipAddress4, 5, 4, 1, 1)
        self.dateIn = QtWidgets.QDateEdit(self.config_project)
        self.dateIn.setObjectName("dateIn")
        self.gridLayout_2.addWidget(self.dateIn, 3, 3, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.config_project)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.app1 = QtWidgets.QLineEdit(self.config_project)
        self.app1.setObjectName("app1")
        self.gridLayout_2.addWidget(self.app1, 4, 1, 1, 1)
        self.specBid = QtWidgets.QLineEdit(self.config_project)
        self.specBid.setObjectName("specBid")
        self.gridLayout_2.addWidget(self.specBid, 2, 1, 1, 4)
        self.addPeople = QtWidgets.QPushButton(self.config_project)
        self.addPeople.setObjectName("addPeople")
        self.gridLayout_2.addWidget(self.addPeople, 7, 0, 1, 1)
        self.editPeople = QtWidgets.QPushButton(self.config_project)
        self.editPeople.setObjectName("editPeople")
        self.gridLayout_2.addWidget(self.editPeople, 7, 1, 1, 1)
        self.delPeople = QtWidgets.QPushButton(self.config_project)
        self.delPeople.setObjectName("delPeople")
        self.gridLayout_2.addWidget(self.delPeople, 7, 2, 1, 1)
        self.upTable = QtWidgets.QPushButton(self.config_project)
        self.upTable.setObjectName("upTable")
        self.gridLayout_2.addWidget(self.upTable, 7, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.config_project, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор"))
        self.label_9.setText(_translate("MainWindow", "Номер ревизии"))
        self.label_8.setText(_translate("MainWindow", "IP адрес"))
        self.label_7.setText(_translate("MainWindow", "Экземляры"))
        self.label_4.setText(_translate("MainWindow", "Номер заявки"))
        self.label_11.setText(_translate("MainWindow", "svn"))
        self.label_3.setText(_translate("MainWindow", "Название проекта"))
        self.cache.setText(_translate("MainWindow", "Сброс кеша"))
        self.label_5.setText(_translate("MainWindow", "Время публикации"))
        self.label_10.setText(_translate("MainWindow", "Порт приложения"))
        self.label_6.setText(_translate("MainWindow", "Описание заявки"))
        self.addPeople.setText(_translate("MainWindow", "Добавить сотрудника "))
        self.editPeople.setText(_translate("MainWindow", "Изменить сотрудника"))
        self.delPeople.setText(_translate("MainWindow", "Удалить сотрудника"))
        self.upTable.setText(_translate("MainWindow", "Обновить таблицу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_project), _translate("MainWindow", "Значения"))

