# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.config_project = QtWidgets.QWidget()
        self.config_project.setObjectName("config_project")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config_project)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cache = QtWidgets.QCheckBox(self.config_project)
        self.cache.setEnabled(True)
        self.cache.setAcceptDrops(False)
        self.cache.setChecked(False)
        self.cache.setObjectName("cache")
        self.gridLayout_2.addWidget(self.cache, 1, 4, 1, 1)
        self.portApp = QtWidgets.QLineEdit(self.config_project)
        self.portApp.setObjectName("portApp")
        self.gridLayout_2.addWidget(self.portApp, 8, 1, 1, 1)
        self.delPeople = QtWidgets.QPushButton(self.config_project)
        self.delPeople.setObjectName("delPeople")
        self.gridLayout_2.addWidget(self.delPeople, 10, 2, 1, 1)
        self.numberRev = QtWidgets.QLineEdit(self.config_project)
        self.numberRev.setObjectName("numberRev")
        self.gridLayout_2.addWidget(self.numberRev, 1, 3, 1, 1)
        self.ipAddress3 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress3.setObjectName("ipAddress3")
        self.gridLayout_2.addWidget(self.ipAddress3, 6, 3, 1, 1)
        self.addPeople = QtWidgets.QPushButton(self.config_project)
        self.addPeople.setObjectName("addPeople")
        self.gridLayout_2.addWidget(self.addPeople, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.config_project)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.config_project)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.app1 = QtWidgets.QLineEdit(self.config_project)
        self.app1.setObjectName("app1")
        self.gridLayout_2.addWidget(self.app1, 5, 1, 1, 1)
        self.dateIn = QtWidgets.QDateEdit(self.config_project)
        self.dateIn.setObjectName("dateIn")
        self.gridLayout_2.addWidget(self.dateIn, 4, 3, 1, 2)
        self.ipAddress2 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress2.setObjectName("ipAddress2")
        self.gridLayout_2.addWidget(self.ipAddress2, 6, 2, 1, 1)
        self.upTable = QtWidgets.QPushButton(self.config_project)
        self.upTable.setObjectName("upTable")
        self.gridLayout_2.addWidget(self.upTable, 10, 3, 1, 1)
        self.ipAddress4 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress4.setObjectName("ipAddress4")
        self.gridLayout_2.addWidget(self.ipAddress4, 6, 4, 1, 1)
        self.ipAddress1 = QtWidgets.QLineEdit(self.config_project)
        self.ipAddress1.setObjectName("ipAddress1")
        self.gridLayout_2.addWidget(self.ipAddress1, 6, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.config_project)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 11, 0, 1, 5)
        self.nameProject = QtWidgets.QLineEdit(self.config_project)
        self.nameProject.setObjectName("nameProject")
        self.gridLayout_2.addWidget(self.nameProject, 0, 1, 1, 4)
        self.app2 = QtWidgets.QLineEdit(self.config_project)
        self.app2.setObjectName("app2")
        self.gridLayout_2.addWidget(self.app2, 5, 2, 1, 1)
        self.svn = QtWidgets.QLineEdit(self.config_project)
        self.svn.setObjectName("svn")
        self.gridLayout_2.addWidget(self.svn, 8, 3, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.config_project)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.config_project)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.editPeople = QtWidgets.QPushButton(self.config_project)
        self.editPeople.setObjectName("editPeople")
        self.gridLayout_2.addWidget(self.editPeople, 10, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.config_project)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.app3 = QtWidgets.QLineEdit(self.config_project)
        self.app3.setObjectName("app3")
        self.gridLayout_2.addWidget(self.app3, 5, 3, 1, 1)
        self.numBid = QtWidgets.QLineEdit(self.config_project)
        self.numBid.setObjectName("numBid")
        self.gridLayout_2.addWidget(self.numBid, 1, 1, 1, 1)
        self.timeOut = QtWidgets.QTimeEdit(self.config_project)
        self.timeOut.setObjectName("timeOut")
        self.gridLayout_2.addWidget(self.timeOut, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.config_project)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.app4 = QtWidgets.QLineEdit(self.config_project)
        self.app4.setObjectName("app4")
        self.gridLayout_2.addWidget(self.app4, 5, 4, 1, 1)
        self.timeIn = QtWidgets.QTimeEdit(self.config_project)
        self.timeIn.setObjectName("timeIn")
        self.gridLayout_2.addWidget(self.timeIn, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.config_project)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.config_project)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.config_project)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.config_project)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 7, 0, 1, 1)
        self.vamish1 = QtWidgets.QLineEdit(self.config_project)
        self.vamish1.setObjectName("vamish1")
        self.gridLayout_2.addWidget(self.vamish1, 7, 1, 1, 1)
        self.vamish2 = QtWidgets.QLineEdit(self.config_project)
        self.vamish2.setObjectName("vamish2")
        self.gridLayout_2.addWidget(self.vamish2, 7, 2, 1, 1)
        self.vamish3 = QtWidgets.QLineEdit(self.config_project)
        self.vamish3.setObjectName("vamish3")
        self.gridLayout_2.addWidget(self.vamish3, 7, 3, 1, 1)
        self.vamish4 = QtWidgets.QLineEdit(self.config_project)
        self.vamish4.setObjectName("vamish4")
        self.gridLayout_2.addWidget(self.vamish4, 7, 4, 1, 1)
        self.specBid = QtWidgets.QLineEdit(self.config_project)
        self.specBid.setObjectName("specBid")
        self.gridLayout_2.addWidget(self.specBid, 2, 2, 1, 3)
        self.test1 = QtWidgets.QLineEdit(self.config_project)
        self.test1.setObjectName("test1")
        self.gridLayout_2.addWidget(self.test1, 9, 1, 1, 1)
        self.test2 = QtWidgets.QLineEdit(self.config_project)
        self.test2.setObjectName("test2")
        self.gridLayout_2.addWidget(self.test2, 9, 2, 1, 1)
        self.test3 = QtWidgets.QLineEdit(self.config_project)
        self.test3.setObjectName("test3")
        self.gridLayout_2.addWidget(self.test3, 9, 3, 1, 1)
        self.test4 = QtWidgets.QLineEdit(self.config_project)
        self.test4.setObjectName("test4")
        self.gridLayout_2.addWidget(self.test4, 9, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.config_project)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.numberBid = QtWidgets.QLineEdit(self.config_project)
        self.numberBid.setObjectName("numberBid")
        self.gridLayout_2.addWidget(self.numberBid, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.config_project)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.comandCache = QtWidgets.QLineEdit(self.config_project)
        self.comandCache.setObjectName("comandCache")
        self.gridLayout_2.addWidget(self.comandCache, 3, 1, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.config_project, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nameProject, self.numBid)
        MainWindow.setTabOrder(self.numBid, self.numberRev)
        MainWindow.setTabOrder(self.numberRev, self.cache)
        MainWindow.setTabOrder(self.cache, self.numberBid)
        MainWindow.setTabOrder(self.numberBid, self.specBid)
        MainWindow.setTabOrder(self.specBid, self.comandCache)
        MainWindow.setTabOrder(self.comandCache, self.timeIn)
        MainWindow.setTabOrder(self.timeIn, self.timeOut)
        MainWindow.setTabOrder(self.timeOut, self.dateIn)
        MainWindow.setTabOrder(self.dateIn, self.app1)
        MainWindow.setTabOrder(self.app1, self.app2)
        MainWindow.setTabOrder(self.app2, self.app3)
        MainWindow.setTabOrder(self.app3, self.app4)
        MainWindow.setTabOrder(self.app4, self.ipAddress1)
        MainWindow.setTabOrder(self.ipAddress1, self.ipAddress2)
        MainWindow.setTabOrder(self.ipAddress2, self.ipAddress3)
        MainWindow.setTabOrder(self.ipAddress3, self.ipAddress4)
        MainWindow.setTabOrder(self.ipAddress4, self.vamish1)
        MainWindow.setTabOrder(self.vamish1, self.vamish2)
        MainWindow.setTabOrder(self.vamish2, self.vamish3)
        MainWindow.setTabOrder(self.vamish3, self.vamish4)
        MainWindow.setTabOrder(self.vamish4, self.portApp)
        MainWindow.setTabOrder(self.portApp, self.svn)
        MainWindow.setTabOrder(self.svn, self.test1)
        MainWindow.setTabOrder(self.test1, self.test2)
        MainWindow.setTabOrder(self.test2, self.test3)
        MainWindow.setTabOrder(self.test3, self.test4)
        MainWindow.setTabOrder(self.test4, self.addPeople)
        MainWindow.setTabOrder(self.addPeople, self.upTable)
        MainWindow.setTabOrder(self.upTable, self.delPeople)
        MainWindow.setTabOrder(self.delPeople, self.editPeople)
        MainWindow.setTabOrder(self.editPeople, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.buttonBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор"))
        self.cache.setText(_translate("MainWindow", "Сброс кеша"))
        self.delPeople.setText(_translate("MainWindow", "Удалить сотрудника"))
        self.addPeople.setText(_translate("MainWindow", "Добавить сотрудника "))
        self.label_8.setText(_translate("MainWindow", "IP адрес"))
        self.label_7.setText(_translate("MainWindow", "Экземляры"))
        self.upTable.setText(_translate("MainWindow", "Обновить таблицу"))
        self.label_11.setText(_translate("MainWindow", "svn"))
        self.label_3.setText(_translate("MainWindow", "Название проекта (Р. П)"))
        self.editPeople.setText(_translate("MainWindow", "Изменить сотрудника"))
        self.label_5.setText(_translate("MainWindow", "Время публикации"))
        self.label_10.setText(_translate("MainWindow", "Порт приложения"))
        self.label_9.setText(_translate("MainWindow", "Номер ревизии"))
        self.label_4.setText(_translate("MainWindow", "Номер заявки релиза"))
        self.label_2.setText(_translate("MainWindow", "Адрес для тестеров"))
        self.label.setText(_translate("MainWindow", "КЭШ сервера"))
        self.label_12.setText(_translate("MainWindow", "Номер и описание заявки"))
        self.label_6.setText(_translate("MainWindow", "Команда сброса кэша"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_project), _translate("MainWindow", "Значения"))

